config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :reports, only:[:index, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Dir["public/reports/*"]
  end

  def create
    ReportJob.perform_later
    flash[:notice] = "Estamos processando seu relatório \\o/"
    redirect_to '/reports'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportJobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_report.html.erb
<%= link_to(report.split('/').last, "/reports/#{report.split('/').last}", target: "_blank") %>
<br>

app/views/reports/index.html.erb
<% if flash[:notice] %>
  <b style="color: green"><%= flash[:notice] %></b>
<% end %>

<h3>Relatórios</h3>

<div class="reports">
  <%= render partial: 'report', collection: @reports %>
</div>
<br>

<%= link_to 'reload', reports_path, remote: true %>

<hr>

<%= form_tag("/reports", method: "post") do %>
  <%= submit_tag("Gerar Novo") %>
<% end %>

app/views/reports/index.js.erb
document.querySelector('.reports').innerHTML = "<%= j render partial: 'report', collection: @reports %>"